In [1]:
#Numpy produced by Travis Oliphant, which has been produced fundamentally for scientific computing
#It helps handling multidimensional arrays and matrices, also high level mathematical functions to operate on these arrays

In [2]:
#Numpy array would require much less memory to store same amount of data compared to python list, which helps in reading and writing from an array in a faster manner.

In [5]:
import numpy as np
n_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
n_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
n_array.ndim   #two dimensional array

2

In [7]:
n_array.shape   #size of an array (rows,columns)

(3, 3)

In [8]:
n_array.size   #number of elements (rows*columns)

9

In [9]:
n_array.dtype   # data type of the element

dtype('int32')

In [10]:
n_array.dtype.name

'int32'

In [13]:
#Array Subtraction
a=np.array([1,2,3])
b=np.array([1,2,3])
a-b

#Note: subtract two arrays of equal dimensions

array([0, 0, 0])

In [14]:
#Squaring an array
b**2

array([1, 4, 9], dtype=int32)

In [17]:
#trigonometric function
np.cos(b)   #cosine function

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [18]:
#conditional operator
b<2

array([ True, False, False])

In [22]:
#Matrix multiplication
A1 = np.array([[1,2],[2,3]])
A2 = np.array([[1,2],[2,3]])
A1*A2                                     #element by element multiplication

array([[1, 4],
       [4, 9]])

In [24]:
np.dot(A1,A2)                           #dot product

array([[ 5,  8],
       [ 8, 13]])

In [25]:
#indexing and slicing
n_array[0,1]

2

In [28]:
n_array[0,0:3]

array([1, 2, 3])

In [32]:
#to select entire row
n_array[:,0]

array([1, 4, 7])

In [33]:
#to select entire column
n_array[0,:]

array([1, 2, 3])

In [35]:
#shape manipulation

#Flatten the array
n_array.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
n_array.shape

(3, 3)

In [44]:
n_array.shape=(1,9)  # changing to new shape
n_array

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [45]:
n_array.transpose()

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])